from sqlalchemy.ext.asyncio import AsyncSession
from sqlalchemy import select, desc
import uuid
from typing import List, Tuple
from app.models.project import Project
from slugify import slugify


async def create_project(
    db: AsyncSession,
    user_id: uuid.UUID,
    name: str,
    description: str,
    target_framework: str,
    target_language: str,
) -> Project:
    
    try:
        # If no name or description provided, use AI defaults
        if not name and not description:
            name = "AI Generated Project"
            description = "This project was generated by AI"
        
        # Generate slug from name
        project_slug = slugify(name) if name else slugify("untitled-project")

        project = Project(
            user_id=user_id,
            name=name,
            description=description,
            target_framework=target_framework,
            target_language=target_language,
            slug=project_slug
        )
        db.add(project)
        await db.commit()
        await db.refresh(project)
    except Exception as e:
        await db.rollback()
        raise e

    return project


async def get_user_projects(
    db: AsyncSession,
    user_id: uuid.UUID,
    page: int = 1,
    limit: int = 10
) -> Tuple[List[Project], int]:
    """
    Get all projects for a user with pagination.
    Returns (projects, total_count)
    """
    try:
        # Get total count
        count_query = select(Project).filter(Project.user_id == user_id)
        count_result = await db.execute(count_query)
        total_count = len(count_result.fetchall())
        
        # Get projects with pagination
        offset = (page - 1) * limit
        query = (
            select(Project)
            .filter(Project.user_id == user_id)
            .order_by(desc(Project.created_at))
            .offset(offset)
            .limit(limit)
        )
        
        result = await db.execute(query)
        projects = result.scalars().all()
        
        return list(projects), total_count
        
    except Exception as e:
        raise e