"""Added railway encrypted key to user model

Revision ID: bf9af9f94147
Revises: 2caeebd5e2df
Create Date: 2026-02-25 21:13:27.452854

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bf9af9f94147'
down_revision: Union[str, Sequence[str], None] = '2caeebd5e2df'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('railway_api_key_encrypted', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'railway_api_key_encrypted')
    # ### end Alembic commands ###
