"""add_missing_github_token_encrypted

Revision ID: eae534261cf3
Revises: def456abc789
Create Date: 2026-02-23 01:52:30.316166

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'eae534261cf3'
down_revision: Union[str, Sequence[str], None] = 'def456abc789'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('idx_artifacts_project_id'), table_name='artifacts')
    op.drop_index(op.f('idx_artifacts_type'), table_name='artifacts')
    op.drop_table('artifacts')
    op.drop_index(op.f('idx_builds_project_id'), table_name='builds')
    op.drop_table('builds')
    op.drop_table('projects')
    op.drop_index(op.f('idx_messages_project_id_created'), table_name='messages')
    op.drop_table('messages')
    op.add_column('users', sa.Column('github_token_encrypted', sa.Text(), nullable=True))
    op.alter_column('users', 'email',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
    op.alter_column('users', 'username',
               existing_type=sa.VARCHAR(length=100),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'username',
               existing_type=sa.VARCHAR(length=100),
               nullable=True)
    op.alter_column('users', 'email',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
    op.drop_column('users', 'github_token_encrypted')
    op.create_table('messages',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('project_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('role', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('message_type', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('content', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'[]'::jsonb"), autoincrement=False, nullable=False),
    sa.Column('artifact_id', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('metadata', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.CheckConstraint("message_type = ANY (ARRAY['user_prompt'::text, 'plan_approval'::text, 'conductor_text'::text, 'conductor_plan'::text, 'system_event'::text])", name=op.f('check_message_type')),
    sa.CheckConstraint("role = ANY (ARRAY['user'::text, 'conductor'::text, 'system'::text])", name=op.f('check_message_role')),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], name=op.f('messages_project_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('messages_pkey'))
    )
    op.create_index(op.f('idx_messages_project_id_created'), 'messages', ['project_id', sa.literal_column('created_at DESC')], unique=False)
    op.create_table('projects',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('user_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('name', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('description', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('slug', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('git_repo_url', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('git_branch', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('target_framework', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('target_language', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('status', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('latest_deployed_url', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('last_deployed_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('total_builds', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('successful_builds', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('failed_builds', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('projects_user_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('projects_pkey')),
    sa.UniqueConstraint('slug', name=op.f('projects_slug_key'), postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    op.create_table('builds',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('project_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('build_number', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('status', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('raw_plan', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('approved_plan', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('deploy_url', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('error_message', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('started_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('completed_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.CheckConstraint("status = ANY (ARRAY['planning'::text, 'approved'::text, 'building'::text, 'completed'::text, 'failed'::text])", name=op.f('check_build_status')),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], name=op.f('builds_project_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('builds_pkey')),
    sa.UniqueConstraint('project_id', 'build_number', name=op.f('unique_project_build_number'), postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    op.create_index(op.f('idx_builds_project_id'), 'builds', ['project_id'], unique=False)
    op.create_table('artifacts',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('project_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('artifact_type', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('title', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('content', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), autoincrement=False, nullable=False),
    sa.Column('file_storage_url', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.CheckConstraint("artifact_type = ANY (ARRAY['plan'::text, 'deployment'::text])", name=op.f('check_artifact_type')),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], name=op.f('artifacts_project_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('artifacts_pkey'))
    )
    op.create_index(op.f('idx_artifacts_type'), 'artifacts', ['artifact_type'], unique=False)
    op.create_index(op.f('idx_artifacts_project_id'), 'artifacts', ['project_id'], unique=False)
    # ### end Alembic commands ###
